spring.application.name=trading-project
server.port=5454
# Redis Connection Configuration
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6380
spring.data.redis.host=localhost
spring.data.redis.port=6380
# Optional: Set a default Time-To-Live (TTL) for your cache (e.g., 10 minutes)
spring.cache.redis.time-to-live=600000
# Updated Driver
# Added port and disabled SSL (common for local dev)
# Dynamic Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings to auto-create tables in your cloud database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

