spring.application.name=trading-project
server.port=5454
# Redis Connection Configuration
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6380
spring.data.redis.host=localhost
spring.data.redis.port=6380
# Optional: Set a default Time-To-Live (TTL) for your cache (e.g., 10 minutes)
spring.cache.redis.time-to-live=600000
# Updated Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Added port and disabled SSL (common for local dev)
spring.datasource.url=jdbc:mysql://localhost:3306/trades?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=password
stripe.api.key=${STRIPE_SECRET_KEY}
razorpay.api.key=${RAZORPAY_SECRET_KEY}
razorpay.api.secret=${RAZORPAY_SECRET_SECRET}
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


